# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e9a36eee0ed187c9879c330b17d13576c7bae088893cb23f89294eb44b9d0ab8c9e6bd6dbc8e8e4816662bfea2145570a759bd41958d750861aa926640c3115

test:
  secret_key_base: 996355f4e3b67032bbc7ddcd3004018137762178931806f95cd25504a5d0bbb88b44b61aaec8945053ef1175d663bea381ddae44bd86bce8ffdfc79c730b7e56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
